sudo: false

language: rust

rust:
  - stable
  - nightly

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo run -- < README.md

cache: cargo

jobs:
  include:
    - stage: format
      before_install: rustup component add rustfmt-preview
      script: cargo fmt -- --check
      rust: beta

stages:
  - format
